### PR TITLE
Toolset - Add a setting to look for NSS files before decompiling NCS

### PR DESCRIPTION
**Pull request by JoeNotCharles**
Adds a new "Search for NSS files before decompiling NCS resources" setting. If it's enabled, opening an NCS resource will first open a file dialog to let the user choose an NSS file to load, and fall back to decompiling the NCS if the user cancels or the load fails.

### CODE REVIEW

**Comment by th3w1zard1** [comment]
Is this specifically for the 'extract selected' button or is this feature more generally used by various frontend code?

**Comment by JoeNotCharles** [comment]
It's any time an NCS is loaded into the NSS editor, to get a text file to
populate the editor with. I don't think it would affect "extract selected"
at all since IIUC that doesn't open the editor, but I didn't test it.

**Comment by th3w1zard1** [comment]
OK I think I'm understanding. This just prompts the user to open a NSS anytime NCS is attempted to be loaded. Not as complex as I thought.

I feel we should do some validation to ensure it matches the NCS. Otherwise the user may pick something that doesn't match.
The NCS class contains various methods/attributes for working with NCS files: we should first compile the user-chosen NSS and ensure it matches the NCS, similar to how DeNCS does it.

Additionally if the user is attempting to load a NCS from a bif, the NSS should always be right next to it. Perhaps the dialog you've created should load the NSS automatically in that instance?

Potentially could auto-download the source scripts from their repo, similar to the KitsDownloader and the Help booklet downloader.

**Comment by JoeNotCharles** [comment]
That's a good idea. How about defaulting the new pref to False and labeling
it "EXPERIMENTAL" until we have time to make those improvements?

I was thinking of having a search path:

1. an optional user-specified dir (in case I have some scripts I've edited
and checked in to source control, and want to re-load one whenever I open
the corresponding NCS - the decompiler would lose stuff like comments and
variable names)
2. the override dir (maybe?)
3. any script with the same resname in the same place as the NSS
4. the Vanilla_Kotor scripts (wrinkle: that archive contains two subdirs
for TSL, one "Vanilla" and one for the Restored Content mod, we should
figure out an interface for users to choose between them)

There's enough design questions about this that I just punted and opened a
manual dialog every time for now.

**Pull request closed without merging**
