### PR TITLE
 Add a setting to look for NSS files before decompiling NCS

### PR DESCRIPTION
**Pull request by JoeNotCharles**
<when opening an NCS resource, let the user pick an NSS from Vanilla_KOTOR_Script_Source instead of decompiling
implemented in PR> #75

### CODE REVIEW

**Comment by th3w1zard1** [comment]
Looks good to me. Worked fine during testing. Please let me know when you'd like this merged. Not sure if you're planning any extra features here or whatnot.

**Comment by JoeNotCharles** [comment]
I won't have time to work on it more for a while, so might as well merge it
now. The biggest thing it's missing is checking that the NSS matches the
NCS for safety, which is why I turned the setting off by default, but I
think we can merge it as a use-at-your-own-risk feature like RIM saving

**Comment by th3w1zard1** [comment]
> I won't have time to work on it more for a while, so might as well merge it now. The biggest thing it's missing is checking that the NSS matches the NCS for safety, which is why I turned the setting off by default, but I think we can merge it as a use-at-your-own-risk feature like RIM saving

That logic alone will be a pain to write, maybe @NickHugi could take a look as the NCS objects are part of his compiler code.

**Comment by th3w1zard1** [comment]
idea improved upon and implemented in another PR.

**Pull request closed without merging**
